### ISSUE TITLE
Reader crash

### ISSUE THREAD

**Issue by tcolgate** [QubitProducts/logspray#7]
```E0429 10:39:26.390053       1 dockersource.go:143] error retrieving container exit info,  Error: No such container: a587543db2419f0f64c9bd6908f9b7015a6f9c8a4f1ce930355068caebeba578
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x90308a]

goroutine 23730 [running]:
github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sinks/remote.(*MessageWriter).Close(0xc4202e3d70, 0xc4204af6a8, 0xc4203e3dd0)
        /home/tristan/src/infra-kube-base/go/src/github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sinks/remote/remote.go:118 +0x2a
github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sinks/relabeler.(*MessageWriter).Close(0xc4205bc480, 0xc42050d380, 0x40)
        /home/tristan/src/infra-kube-base/go/src/github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sinks/relabeler/relabeler.go:107 +0x34
github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sources.(*targetSet).readAllFromTarget(0xc42007ac40, 0xb5eac0, 0xc42007ac00, 0xb59c40, 0xc4205bc480, 0xc4205bc460, 0x1, 0xb56c80, 0xc42008a050)
        /home/tristan/src/infra-kube-base/go/src/github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sources/reader.go:153 +0x621
github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sources.(*targetSet).addSource(0xc42007ac40, 0xb5eac0, 0xc42007ac00, 0xb56ce0, 0xc42000b680, 0xc4205bc460, 0x1)
        /home/tristan/src/infra-kube-base/go/src/github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sources/reader.go:123 +0x19d
created by github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sources.ReadAllTargets
        /home/tristan/src/infra-kube-base/go/src/github.com/qubitdigital/logspray/vendor/github.com/QubitProducts/logspray/sources/reader.go:97 +0x56c
```

**Comment by tcolgate** [comment]
Fixed in 84cd66fa580406345fd76343dae2c1c2d12d94a0
